# Configuration file for experiment 1 (search topology with only VGG blocks with kernel 3)

QNAS:
    crossover_rate: 0.1
    max_generations: 100
    max_num_nodes: 1
    num_quantum_ind: 3
    repetition: 1
    replace_method: best
    update_quantum_gen: 1
    update_quantum_rate: 0.9

    layer_dict:  {
        'vgg_d_3': {'cell': 'DownscalingCell', 'block': 'VGGBlock', 'kernel': 3, 'prob': 1/3},
        'vgg_n_3': {'cell': 'NonscalingCell',  'block': 'VGGBlock', 'kernel': 3, 'prob': 1/3},
        'vgg_u_3': {'cell': 'UpscalingCell',   'block': 'VGGBlock', 'kernel': 3, 'prob': 1/3},
    }

train:
    batch_size: 32
    epochs: 30
    eval_epochs: 6
    initializations: 1
    folds: 5
    stem_filters: 16
    max_depth: 4

    # Dataset
    data_path: spleen_dataset/data/Task09_Spleen_preprocessed/
    image_size: 128
    skip_slices: 1
    num_channels: 1
    num_classes: 2
    data_augmentation: True
