# Configuration file for experiment 3 (search blocks but keeping topology found in experiment_1)

QNAS:
    crossover_rate: 0.1
    max_generations: 100
    max_num_nodes: 10
    num_quantum_ind: 9
    repetition: 1
    replace_method: best
    update_quantum_gen: 1
    update_quantum_rate: 0.9

    layer_dict:  {
        'den_3': {'block': 'DenseBlock',     'kernel': 3, 'prob': 1/13},
        'den_5': {'block': 'DenseBlock',     'kernel': 5, 'prob': 1/13},
        'den_7': {'block': 'DenseBlock',     'kernel': 7, 'prob': 1/13},
        'inc_3': {'block': 'InceptionBlock', 'kernel': 3, 'prob': 1/13},
        'inc_5': {'block': 'InceptionBlock', 'kernel': 5, 'prob': 1/13},
        'inc_7': {'block': 'InceptionBlock', 'kernel': 7, 'prob': 1/13},
        'ide':   {'block': 'IdentityBlock',               'prob': 1/13},
        'res_3': {'block': 'ResNetBlock',    'kernel': 3, 'prob': 1/13},
        'res_5': {'block': 'ResNetBlock',    'kernel': 5, 'prob': 1/13},
        'res_7': {'block': 'ResNetBlock',    'kernel': 7, 'prob': 1/13},
        'vgg_3': {'block': 'VGGBlock',       'kernel': 3, 'prob': 1/13},
        'vgg_5': {'block': 'VGGBlock',       'kernel': 5, 'prob': 1/13},
        'vgg_7': {'block': 'VGGBlock',       'kernel': 7, 'prob': 1/13},
    }

    # the cell list must be set accordingly to experiment_1 output
    cell_list: [
        'DownscalingCell',
        'NonscalingCell', 
        'DownscalingCell', 
        'NonscalingCell', 
        'NonscalingCell', 
        'NonscalingCell', 
        'DownscalingCell', 
        'NonscalingCell', 
        'DownscalingCell',
        'NonscalingCell', 
    ]

train:
    batch_size: 32
    epochs: 30
    eval_epochs: 6
    initializations: 1
    folds: 5
    stem_filters: 16
    max_depth: 4

    gpu_selected: '0'
    threads: 4

    # Dataset
    data_path: spleen_dataset/data/Task09_Spleen_preprocessed/
    image_size: 128
    skip_slices: 1
    num_channels: 1
    num_classes: 2
    data_augmentation: True
